spring:
  datasource:
    askconfig:
      jdbc-url: jdbc:sqlserver://121.201.76.175:1322;databaseName=askconfig;integratedSecurity=false;
      username: ask_lepqIEQ88
      password: tz_1FzgPRSTzUmpl
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    askdata4:
      jdbc-url: jdbc:sqlserver://121.201.76.150;databaseName=askdata4;integratedSecurity=false;
      username: bil893nsoi
      password: y3wn#pq85nzwal
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    askdata5:
      jdbc-url: jdbc:sqlserver://121.201.76.175;databaseName=askdata5;integratedSecurity=false;
      username: bil893nsoi
      password: y3wn#pq85nzwal
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    asklog:
      jdbc-url: jdbc:sqlserver://121.201.76.150;databaseName=AskLogDB;integratedSecurity=false;
      username: bil893nsoi
      password: y3wn#pq85nzwal
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    askcenter:
      jdbc-url: jdbc:sqlserver://121.201.76.175;databaseName=Askcenter;integratedSecurity=false;loginTimeout=600
      username: bil893nsoi
      password: y3wn#pq85nzwal
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    produce:
      username: my8test
      password: QE34ki_bvmk63a
      jdbc-url: jdbc:mysql://10.10.10.53:3309/pd_produce_db?serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: mongodb://219.238.238.81:27018,219.238.238.40:27018,219.238.238.81:27021/authreply?readPreference=primary

logging:
  level:
    root: info