spring:
  datasource:
    askconfig:
      jdbc-url: jdbc:sqlserver://219.238.238.120;databaseName=askconfig_20160505;integratedSecurity=false;
      username: ask_120tPn
      password: fegs345DF#wQcvW
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    askdata4:
      jdbc-url: jdbc:sqlserver://219.238.238.120:1322;databaseName=askdata4_20160505;integratedSecurity=false;
      username: ask_120tPn
      password: fegs345DF#wQcvW
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    asklog:
      jdbc-url: jdbc:sqlserver://219.238.238.120;databaseName=AskLogDB;integratedSecurity=false;
      username: ask_120tPn
      password: fegs345DF#wQcvW
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    askcenter:
      jdbc-url: jdbc:sqlserver://219.238.238.120:1322;databaseName=Askcenter;integratedSecurity=false;loginTimeout=600
      username: ask_120tPn
      password: fegs345DF#wQcvW
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    produce:
      username: root
      password: 123456
      jdbc-url: jdbc:mysql://192.168.204.129:3306/pd_produce_dev_db?serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: mongodb://219.238.238.81:27018,219.238.238.40:27018,219.238.238.81:27021/authreply?readPreference=primary

logging:
  level:
    root: info